Update twrp_build.yml

diff --git a/.github/workflows/twrp_build.yml b/.github/workflows/twrp_build.yml
--- a/.github/workflows/twrp_build.yml
+++ b/.github/workflows/twrp_build.yml
@@ -42,7 +42,8 @@ jobs:
       run: |
         mkdir twrp
         cd twrp
-        repo init --depth=1 -u git://github.com/DereckySany/platform_manifest_twrp_omni.git -b twrp-8.0 || echo "init_failed" > /tmp/err
+        repo init --depth=1 -u git://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-8.1 || echo "init_failed" > /tmp/err
+      #repo init --depth=1 -u git://github.com/DereckySany/platform_manifest_twrp_omni.git -b twrp-8.0 || echo "init_failed" > /tmp/err
 
     - name: Check for errors
       run: |
