Update twrp_build.yml

diff --git a/.github/workflows/twrp_build.yml b/.github/workflows/twrp_build.yml
--- a/.github/workflows/twrp_build.yml
+++ b/.github/workflows/twrp_build.yml
@@ -15,6 +15,16 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v3
 
+    - name: Delete failed workflow runs
+      run: |
+        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+             -H "Accept: application/vnd.github.v3+json" \
+             https://api.github.com/repos/${{ github.repository }}/actions/runs \
+             | jq -r '.workflow_runs[] | select(.conclusion == "failure") | .id' \
+             | xargs -I {} curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+             -H "Accept: application/vnd.github.v3+json" \
+             https://api.github.com/repos/${{ github.repository }}/actions/runs/{}
+             
     - name: Install dependencies
       run: sudo apt-get update && sudo apt-get install -y make curl git wget
 
@@ -28,11 +38,18 @@ jobs:
         sudo mv repo /usr/local/bin/
 
     - name: Initialize a shallow clone
+      id: init
       run: |
         mkdir twrp
         cd twrp
-        repo init --depth=1 -u git://github.com/DereckySany/platform_manifest_twrp_omni.git -b twrp-8.0
-      if: success()
+        repo init --depth=1 -u git://github.com/DereckySany/platform_manifest_twrp_omni.git -b twrp-8.0 || echo "init_failed" > /tmp/err
+
+    - name: Check for errors
+      run: |
+        if [ -f /tmp/err ]; then
+          echo "Error initializing the repository"
+          exit 1
+        fi
 
     - name: Sync up repo
       run: |
